services:
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - postgres
    command: python manage.py runserver 0.0.0.0:8000

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
      
# volumes:
#   postgres_data: